define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Térkép",
      "lblLocation": "Hely",
      "lblContent": "Tartalom",
      "lblPopup": "Felugró ablak",
      "lblControls": "Extrák",
      "lblOverview": "Átnézeti térkép",
      "lblLegend": "Jelmagyarázat",
      "lblGeocoder": "Címek, helyek és vektoros elemek keresője",
      "lblGeocoderNoFeatures": "Cím- és helykereső",
      "tooltipGeocoder": "Lehetővé teszi az olvasóknak címek, helyek és/vagy vektoros elemek keresését a térképen. A keresési beállítások a webtérkép elemoldalán adhatók meg a Beállítások > Webtérkép > Alkalmazás > Helyek keresése parancs választásával.",
      "tooltipGeocoderNoEdit": "Lehetővé teszi az olvasóknak címek, helyek és/vagy vektoros elemek keresését a térképen.",
      "tooltipGeocoderNoFeatures": "Lehetővé teszi az olvasóknak címek, helyek és/vagy vektoros elemek keresését ezen a térképen. A vektoros elemek keresésének engedélyezéséhez kérje meg a térkép tulajdonosát, hogy konfigurálja a keresést a webtérkép elemoldalán a Beállítások > Webtérkép > Alkalmazás > Helyek keresése parancs választásával.",
      "linkGeocoder": "Térképkeresés konfigurálása",
      "tooltipGeocoderLink": "Ezt a hivatkozást használva konfigurálhatja a vektoros elemek keresését és az egyéb keresési beállításokat. További információt az ArcGIS következő súgótémakörében talál: „A vektoros elemek keresésének konfigurálása”.",
      "lblEsriGeocoder": "World Placefinder",
      "placeholderGenericGeocoder": "Cím vagy hely keresése",
      "loadingTitle": "Cím betöltése",
      "entry": "Bejegyzés",
      "entries": "Bejegyzések",
      "section": "Szekció",
      "sections": "Szekciók",
      "and": "és",
      "action": "Művelet a szekcióban",
      "actions": "Művelet a szekciókban",
      "originalWebmap": "A(z) %TPL_NAME% közzétételéhez használt térkép",
      "browseMaps": "Térkép kiválasztása",
      "createMap": "Térkép létrehozása",
      "noResults": "Nincs találat",
      "loadingResults": "Betöltés...",
      "current": "Aktuális térkép",
      "select": "Térkép kiválasztása vagy létrehozása",
      "newMap": "Újonnan kiválasztott térkép",
      "newCreatedMap": "Újonnan létrehozott térkép",
      "webmapDefault": "Térkép alapértelmezése",
      "customCfg": "Egyéni konfiguráció",
      "tooltipLocation": "Határozza meg azt a helyet, amelyet a térkép meg fog jeleníteni.",
      "tooltipContent": "Határozza meg a látható rétegeket.",
      "tooltipPopup": "Válasszon felugró ablakot, amely a térkép megjelenítésekor nyílik meg.",
      "tooltipOverview": "Kisméretű átnézeti térkép megjelenítése a főtérképpel együtt.",
      "tooltipLegend": "Jelmagyarázat megjelenítése a térképen, ami akkor hasznos, ha a térkép sok réteget és szimbólumot tartalmaz.",
      "mapCfgInvite": "Használja ezeket a vezérlőket a térkép konfigurálásához",
      "lblLocationAlt": "Öröklés az első térképtől",
      "tooltipLocationAlt": "A térkép helye a sorozat első térképének helyével van szinkronizálva. A sorozat működésének megváltoztatásához válassza a Beállítások > Térkép beállításai parancsot."
    },
    "configure": {
      "btnReset": "Visszaállítás",
      "btnCancel": "Mégse",
      "tocTitle": "Térkép tartalma",
      "tocExplain": "Válassza ki a megjelenítendő rétegeket.",
      "tocNoData": "Egy réteg sem konfigurálható.",
      "tocSave": "Térkép tartalmának mentése",
      "extentTitle": "Térkép helye",
      "extentExplain": "A térkép mozgatásával és nagyításával/kicsinyítésével határozza meg, hogyan fog megjelenni a térkép az olvasóknak.",
      "extentSave": "Térkép helyének mentése",
      "popupTitle": "Térkép felugró ablaka",
      "popupExplain": "Kattintson egy vektoros elemre a megjeleníteni kívánt felugró ablak megnyitásához.",
      "popupSave": "Felugró ablak konfigurációjának mentése",
      "hintNavigation": "A térképnavigáció le van tiltva."
    },
    "editor": {
      "loading": "Várjon, amíg a térképszerkesztő betöltődik",
      "newTitle": "Új térkép létrehozása",
      "editTitle": "Térkép szerkesztése",
      "titleLbl": "Cím",
      "titlePh": "Térkép címe...",
      "folderLbl": "A térkép ugyanabban a mappában lesz létrehozva, mint a történet.",
      "creating": "Térkép létrehozása",
      "saving": "Térkép mentése",
      "success": "Térkép mentve",
      "successCreate": "Térkép létrehozva",
      "cancelTitle": "Elveti a nem mentett módosításokat?",
      "close": "Bezárás",
      "save": "Mentés",
      "confirm": "Igen, bezárom a térképet",
      "deny": "Nem, folytatom a munkát",
      "errorDuplicate": "Már van ilyen című térképe",
      "errorCreate": "Nem sikerült létrehozni a térképet. Próbálja meg újra.",
      "errorSave": "Nem sikerült menteni a térképet. Próbálja meg újra.",
      "notavailable1": "A térképek létrehozása és szerkesztése technikai korlátozás miatt nem támogatott a Firefox böngészőben. A történetet létrehozhatja egy másik böngészőben, vagy kipróbálhatja a következő megoldást.",
      "notavailable2": "A térképek létrehozása és szerkesztése nem támogatott, mivel a(z) %PRODUCT% nem tartalmazza a story mapeket kezelő alkalmazást. További információért forduljon az ArcGIS adminisztrátorához.",
      "notavailable3": "A térképek létrehozása és szerkesztése nem támogatott a Portal for ArcGIS ezen verziójában (ehhez 10.4-es vagy újabb verzió szükséges). További információért forduljon az ArcGIS adminisztrátorához.",
      "notavailable4": "Létrehozhat egy térképet a %MV% használatával, majd visszatérhet ide, és hozzáadhatja a történetéhez.",
      "notavailable5": "Szerkesztheti a térképet a %MV% használatával, majd visszatérhet ide, majd a %apply% után megtekintheti a módosításait.",
      "notavailable6": "térképnézegető",
      "notavailable7": "térkép újbóli betöltése"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Saját szervezet",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Saját tartalom",
        "favoritesLabel": "Saját kedvencek"
      },
      "title": "Térkép kiválasztása",
      "searchTitle": "Keresés",
      "ok": "OK",
      "cancel": "Mégse",
      "placeholder": "Adja meg a keresőkifejezést vagy a webtérkép azonosítóját..."
    }
  }
});