define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Žemėlapis",
      "lblLocation": "Vieta",
      "lblContent": "Turinys",
      "lblPopup": "Iškylantis langas",
      "lblControls": "Priedai",
      "lblOverview": "Apžvalga",
      "lblLegend": "Legenda",
      "lblGeocoder": "Adreso, vietos ir elementų ieškiklis",
      "lblGeocoderNoFeatures": "Adreso arba vietos ieškiklis",
      "tooltipGeocoder": "Leiskite skaitytojams ieškoti adresų, vietų ir (arba) elementų jūsų žemėlapyje. Paieškos parinktis galima sukonfigūruoti internetinio žemėlapio elementų puslapyje pasirinkus Parametrai > Internetinis žemėlapis > Aplikacija > Ieškoti vietų.",
      "tooltipGeocoderNoEdit": "Leiskite skaitytojams žemėlapyje ieškoti adresų, vietų ir (arba) elementų.",
      "tooltipGeocoderNoFeatures": "Leiskite skaitytojams žemėlapyje ieškoti adresų ir vietų. Norėdami įgalinti elementų paiešką, paprašykite žemėlapio savininko ją sukonfigūruoti internetinio žemėlapio elementų puslapyje pasirinkus Parametrai > Internetinis žemėlapis > Aplikacija > Ieškoti vietų.",
      "linkGeocoder": "Konfigūruoti žemėlapio paiešką",
      "tooltipGeocoderLink": "Naudokite šią nuorodą norėdami sukonfigūruoti elementų paiešką ir kitas paieškos parinktis. Daugiau informacijos ieškokite ArcGIS žinyno temoje &quot;Konfigūruoti elementų paiešką&quot;.",
      "lblEsriGeocoder": "Pasaulio vietovių ieškiklis",
      "placeholderGenericGeocoder": "Surasti adresą arba vietą",
      "loadingTitle": "Įkeliamas pavadinimas",
      "entry": "Įrašas",
      "entries": "Įrašai",
      "section": "Skiltis",
      "sections": "Skiltys",
      "and": "ir",
      "action": "Veiksmas skiltyje",
      "actions": "Veiksmai skiltyse",
      "originalWebmap": "Žemėlapis, naudojamas publikuoti %TPL_NAME%",
      "browseMaps": "Pasirinkti žemėlapį",
      "createMap": "Kurti žemėlapį",
      "noResults": "Nieko nerasta",
      "loadingResults": "Įkeliama...",
      "current": "Esamas žemėlapis",
      "select": "Pasirinkti arba kurti žemėlapį",
      "newMap": "Naujai pasirinktas žemėlapis",
      "newCreatedMap": "Naujai sukurtas žemėlapis",
      "webmapDefault": "Numatytieji žemėlapio nustatymai",
      "customCfg": "Adaptuota konfigūracija",
      "tooltipLocation": "Nustatykite vietą, kurią rodys šis žemėlapis.",
      "tooltipContent": "Nustatykite matomus sluoksnius.",
      "tooltipPopup": "Pasirinkite iškylantį langą, kuris bus atidarytas, kai bus rodomas šis žemėlapis.",
      "tooltipOverview": "Kartu su pagrindiniu žemėlapiu rodyti mažą apžvalgos žemėlapį.",
      "tooltipLegend": "Žemėlapyje rodyti žemėlapio legendą. Tai naudinga, kai žemėlapyje yra daug sluoksnių ir simbolių.",
      "mapCfgInvite": "Konfigūruokite žemėlapį naudodami šiuos valdiklius",
      "lblLocationAlt": "Paveldėta iš pirmo žemėlapio",
      "tooltipLocationAlt": "Šio žemėlapio vieta sinchronizuojama su pirmu sekos žemėlapiu. Norėdami pakeisti šį savo sekos veikimą, eikite į Nustatymai > Žemėlapio parinktys."
    },
    "configure": {
      "btnReset": "Atkurti",
      "btnCancel": "Atšaukti",
      "tocTitle": "Žemėlapio turinys",
      "tocExplain": "Pasirinkite, kurie sluoksniai bus rodomi.",
      "tocNoData": "Nėra konfigūruotino sluoksnio.",
      "tocSave": "Išsaugoti žemėlapio turinį",
      "extentTitle": "Žemėlapio vieta",
      "extentExplain": "Perstumkite žemėlapį ir keiskite jo mastelį, kad nustatytumėte, kaip jis atrodys skaitytojams.",
      "extentSave": "Išsaugoti žemėlapio vietą",
      "popupTitle": "Žemėlapio iškylantis langas",
      "popupExplain": "Spustelėkite elementą, kad atidarytumėte norimą rodyti iškylantį langą.",
      "popupSave": "Įrašyti iškylančio lango konfigūraciją",
      "hintNavigation": "Žemėlapio navigacija išjungta."
    },
    "editor": {
      "loading": "Palaukite, kol žemėlapių rengyklė pasikraus",
      "newTitle": "Kurti naują žemėlapį",
      "editTitle": "Redaguoti žemėlapį",
      "titleLbl": "Antraštė",
      "titlePh": "Žemėlapio pavadinimas...",
      "folderLbl": "Žemėlapis bus sukurtas tame pačiame aplanke kaip ir pasakojimas.",
      "creating": "Kuriamas žemėlapis",
      "saving": "Įrašomas žemėlapis",
      "success": "Žemėlapis įrašytas",
      "successCreate": "Žemėlapis sukurtas",
      "cancelTitle": "Atsisakyti neįrašytų pakeitimų?",
      "close": "Uždaryti",
      "save": "Išsaugoti",
      "confirm": "Taip, uždaryti žemėlapį",
      "deny": "Ne, palikti atidarytą",
      "errorDuplicate": "Žemėlapis tokiu pavadinimu jau yra",
      "errorCreate": "Žemėlapio sukurti nepavyko. Pabandykite dar kartą.",
      "errorSave": "Nepavyko išsaugoti žemėlapio. Pabandykite dar kartą.",
      "notavailable1": "Deja, naršyklėje Firefox žemėlapio kūrimas arba redagavimas nepalaikomas dėl techninių galimybių ribotumo. Pasakojimą verčiau kurti kitą žiniatinklio naršykle arba pasitelkite problemos sprendimą.",
      "notavailable2": "Deja, žemėlapio kūrimas arba redagavimas nepalaikomas, nes pasakojimo aplikacijos nėra %PRODUCT%. Norėdami gauti daugiau informacijos, susisiekite su ArcGIS administratoriumi.",
      "notavailable3": "Deja, pasakojimo kūrimas arba redagavimas nepalaikomas šioje Portal for ArcGIS versijoje (reikalinga10.4 arba naujesnė versija). Norėdami gauti daugiau informacijos, susisiekite su ArcGIS administratoriumi.",
      "notavailable4": "Galite sukurti žemėlapį naudodami %MV%, tada grįžti čia ir įtraukti jį į savo pasakojimą.",
      "notavailable5": "Žemėlapį galite redaguoti naudodami %MV%, grįžti čia ir %apply%, kad matytumėte savo pakeitimus",
      "notavailable6": "žemėlapių peržiūros programa",
      "notavailable7": "įkelti žemėlapį iš naujo"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Mano organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Turinys",
        "favoritesLabel": "Mėgstamiausi"
      },
      "title": "Pasirinkti žemėlapį",
      "searchTitle": "Ieškoti",
      "ok": "Gerai",
      "cancel": "Atšaukti",
      "placeholder": "Įveskite paieškos terminą arba interneto žemėlapio ID..."
    }
  }
});