define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Mapa",
      "lblLocation": "Ubicació",
      "lblContent": "Contingut",
      "lblPopup": "Finestra emergent",
      "lblControls": "Extres",
      "lblOverview": "Mapa de visualització general",
      "lblLegend": "Llegenda",
      "lblGeocoder": "Cercador d'adreces, llocs i entitats",
      "lblGeocoderNoFeatures": "Cercador d'adreces i llocs",
      "tooltipGeocoder": "Permeteu que els vostres lectors cerquin adreces, llocs i entitats al mapa. Les opcions de cerca es poden configurar a la pàgina de l'element del mapa web a Configuració > Mapa web > Aplicació > Cerca ubicacions.",
      "tooltipGeocoderNoEdit": "Permeteu que els vostres lectors cerquin adreces, llocs i entitats al mapa.",
      "tooltipGeocoderNoFeatures": "Permeteu que els vostres lectors cerquin adreces i llocs al mapa. Per habilitar la cerca d'entitats, demaneu al propietari d'aquest mapa que la configuri a la pàgina de l'element del mapa web a Configuració > Mapa web > Aplicació > Cerca ubicacions.",
      "linkGeocoder": "Configura la cerca del mapa",
      "tooltipGeocoderLink": "Utilitzeu aquest enllaç per configurar la cerca d'entitats i altres opcions de cerca. Consulteu el tema de l'ajuda de l'ArcGIS \"Configuració de la cerca d'entitats\" per obtenir més informació.",
      "lblEsriGeocoder": "Cercador de llocs del món",
      "placeholderGenericGeocoder": "Cerca una adreça o un lloc",
      "loadingTitle": "S'està carregant el títol",
      "entry": "Entrada",
      "entries": "Entrades",
      "section": "Secció",
      "sections": "Seccions",
      "and": "i",
      "action": "Acció en una secció",
      "actions": "Acció en seccions",
      "originalWebmap": "Mapa utilitzat per publicar %TPL_NAME%",
      "browseMaps": "Selecciona un mapa",
      "createMap": "Crea un mapa",
      "noResults": "No s'ha trobat cap resultat",
      "loadingResults": "S'està carregant...",
      "current": "Mapa actual",
      "select": "Selecciona o crea un mapa",
      "newMap": "Mapa acabat de seleccionar",
      "newCreatedMap": "Mapa acabat de crear",
      "webmapDefault": "Per defecte del mapa",
      "customCfg": "Configuració personalitzada",
      "tooltipLocation": "Definiu la ubicació que es mostrarà en aquest mapa.",
      "tooltipContent": "Definiu les capes visibles.",
      "tooltipPopup": "Trieu la finestra emergent que s'obrirà quan es mostri aquest mapa.",
      "tooltipOverview": "Mostreu un mapa de visualització general petit juntament amb el mapa principal.",
      "tooltipLegend": "Mostreu la llegenda del mapa al mapa. És útil quan el mapa té moltes capes i símbols.",
      "mapCfgInvite": "Utilitzeu aquests controls per configurar el mapa",
      "lblLocationAlt": "Heretat del primer mapa",
      "tooltipLocationAlt": "La ubicació d'aquest mapa se sincronitza amb el primer mapa de la sèrie. Per canviar aquest comportament de la sèrie, aneu a Configuració > Opcions del mapa."
    },
    "configure": {
      "btnReset": "Restableix",
      "btnCancel": "Cancel·la",
      "tocTitle": "Contingut del mapa",
      "tocExplain": "Seleccioneu les capes que es mostraran.",
      "tocNoData": "No es pot configurar cap capa.",
      "tocSave": "Desa el contingut del mapa",
      "extentTitle": "Ubicació del mapa",
      "extentExplain": "Apliqueu el zoom i la panoràmica al mapa per definir l'aspecte que tindrà per als lectors.",
      "extentSave": "Desa la ubicació del mapa",
      "popupTitle": "Finestra emergent del mapa",
      "popupExplain": "Feu clic en una entitat per obrir la finestra emergent que voleu mostrar.",
      "popupSave": "Desa la configuració de la finestra emergent",
      "hintNavigation": "La navegació del mapa està deshabilitada."
    },
    "editor": {
      "loading": "Espereu mentre es carrega l'editor del mapa",
      "newTitle": "Crea un mapa nou",
      "editTitle": "Edita el mapa",
      "titleLbl": "Títol",
      "titlePh": "Títol del mapa...",
      "folderLbl": "El mapa es crearà a la mateixa carpeta que la història.",
      "creating": "S'està creant el mapa",
      "saving": "S'està desant el mapa",
      "success": "Mapa desat",
      "successCreate": "Mapa creat",
      "cancelTitle": "Voleu descartar tots els canvis sense desar?",
      "close": "Tanca",
      "save": "Desa",
      "confirm": "Sí, tanca el mapa",
      "deny": "No, continua treballant",
      "errorDuplicate": "Ja teniu un mapa amb aquest títol",
      "errorCreate": "No es pot crear el mapa. Torneu-ho a provar.",
      "errorSave": "No es pot desar el mapa. Torneu-ho a provar.",
      "notavailable1": "A causa d'una limitació tècnica, no s'admeten la creació ni l'edició de mapes amb el Firefox. Si ho preferiu, podeu crear la història en un navegador web diferent o fer servir la solució alternativa següent.",
      "notavailable2": "No s'admeten la creació ni l'edició de mapes perquè l'aplicació de l'story map no està allotjada al %PRODUCT%. Poseu-vos en contacte amb el vostre administrador de l'ArcGIS per obtenir més informació.",
      "notavailable3": "No s'admeten la creació ni l'edició de mapes amb aquesta versió del Portal for ArcGIS (es necessita la versió 10.4 o posterior). Poseu-vos en contacte amb el vostre administrador de l'ArcGIS per obtenir més informació.",
      "notavailable4": "Podeu crear un mapa amb el %MV% i després tornar aquí per afegir-lo a la vostra història.",
      "notavailable5": "Podeu editar el mapa amb el %MV%, tornar aquí i %apply% per veure els canvis.",
      "notavailable6": "visor de mapes",
      "notavailable7": "torna a carregar el mapa"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "La meva organització",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "El meu contingut",
        "favoritesLabel": "Els meus favorits"
      },
      "title": "Selecciona un mapa",
      "searchTitle": "Cerca",
      "ok": "D'acord",
      "cancel": "Cancel·la",
      "placeholder": "Introduïu un terme de cerca o un ID de mapa web..."
    }
  }
});