define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Mapa",
      "lblLocation": "Lokacija",
      "lblContent": "Sadržaj",
      "lblPopup": "Iskačući prozor",
      "lblControls": "Dodaci",
      "lblOverview": "Pregledna mapa",
      "lblLegend": "Legenda",
      "lblGeocoder": "Pretraživač adrese ili mesta",
      "tooltipGeocoder": "Omogućite korisnicima da pronađu adrese i mesta na vašim mapama.",
      "loadingTitle": "Učitavanje naslova",
      "entry": "Unos",
      "entries": "Unosi",
      "section": "Odeljak",
      "sections": "Odeljci",
      "and": "i",
      "action": "Radnja u odeljku",
      "actions": "Radnja u odeljcima",
      "originalWebmap": "Mapa korišćena za objavljivanje %TPL_NAME%",
      "browseMaps": "Izaberi mapu",
      "createMap": "Kreiraj mapu",
      "current": "Trenutna mapa",
      "select": "Izaberi ili kreiraj mapu",
      "newMap": "Nova izabrana mapa",
      "newCreatedMap": "Nova kreirana mapa",
      "webmapDefault": "Podrazumevane postavke mape",
      "customCfg": "Prilagođena konfiguracija",
      "tooltipLocation": "Definišite lokaciju koju će ova mapa da prikazuje.",
      "tooltipContent": "Definišite vidljive slojeve.",
      "tooltipPopup": "Odaberite iskačući prozor koji će da se otvori kada se mapa prikazuje.",
      "tooltipOverview": "Prikažite malu preglednu mapu uz glavnu mapu.",
      "tooltipLegend": "Prikažite legendu mape na mapi, što je korisno kada mapa ima mnogo slojeva i simbola.",
      "mapCfgInvite": "Koristite ove kontrole da konfigurišete mapu",
      "lblLocationAlt": "Nasleđeno iz prve mape",
      "tooltipLocationAlt": "Lokacija ove mape je sinhronizovana sa prvom mapom u nizu. Da biste promenili ovo ponašanje vašeg niza, idite na Postavke > Opcije mape."
    },
    "configure": {
      "btnReset": "Poništi",
      "btnCancel": "Otkaži",
      "tocTitle": "Sadržaj mape",
      "tocExplain": "Izaberite koji slojevi će da budu prikazani.",
      "tocNoData": "Nijedan sloj ne može da bude konfigurisan.",
      "tocSave": "Sačuvaj sadržaj mape",
      "extentTitle": "Lokacija mape",
      "extentExplain": "Pomerajte i zumirajte mapu da definišete kako će da izgleda vašim čitaocima.",
      "extentSave": "Sačuvaj lokaciju mape",
      "popupTitle": "Iskačući prozor mape",
      "popupExplain": "Kliknite na geoobjekat da biste otvorili iskačući prozor koji želite da prikažete.",
      "popupSave": "Sačuvajte konfiguraciju iskačućeg prozora",
      "hintNavigation": "Navigacija mape je onemogućena."
    },
    "editor": {
      "loading": "Sačekajte dok se uređivač mape učitava.",
      "newTitle": "Kreiraj novu mapu",
      "editTitle": "Izmeni mapu",
      "titleLbl": "Naslov",
      "titlePh": "Naslov mape...",
      "folderLbl": "Mapa će da bude kreirana u istoj fascikli kao priča.",
      "creating": "Kreiranje mape",
      "saving": "Čuvanje mape",
      "success": "Mapa je sačuvana",
      "successCreate": "Mapa je kreirana",
      "cancelTitle": "Odbaci sve nesačuvane izmene?",
      "errorDuplicate": "Već imate mapu sa tim naslovom",
      "errorCreate": "Kreiranje mape nije moguće. Pokušajte ponovo.",
      "errorSave": "Čuvanje mape nije moguće. Pokušajte ponovo.",
      "notavailable1": "Žao nam je, kreiranje ili uređivanje mape nije podržano u pregledaču Firefox zbog tehničkih ograničenja. Možda bi trebalo da izgradite priču korišćenjem drugog pregledača ili sledećeg zaobilaznog načina.",
      "notavailable2": "Žao nam je, kreiranje ili uređivanje mape nije podržano jer aplikacija mape sa pričom nije hostovana u %PRODUCT%. Kontaktirajte ArcGIS administratora za više informacija.",
      "notavailable3": "Žao nam je, kreiranje ili uređivanje mape nije podržano na verziji Portal for ArcGIS (zahteva 10.4 ili noviju). Kontaktirajte ArcGIS administratora za više informacija.",
      "notavailable4": "Možete da kreirate mapu korišćenjem %MV%, zatim da se vratite ovde da dodate.",
      "notavailable5": "Možete da kreirate mapu korišćenjem %MV%, zatim da se vratite ovde i %apply% da vidite izmene.",
      "notavailable6": "preglednik mape",
      "notavailable7": "ponovo učitajte mapu"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moj sadržaj",
        "favoritesLabel": "Moj omiljeni sadržaj"
      },
      "title": "Izaberi mapu",
      "searchTitle": "Pretraži",
      "ok": "U redu",
      "cancel": "Otkaži",
      "placeholder": "Unesite stavku pretrage ili ID veb mape..."
    }
  }
});