define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Karta",
      "lblLocation": "Lokacija",
      "lblContent": "Vsebina",
      "lblPopup": "Pojavno okno",
      "lblControls": "Dodatki",
      "lblOverview": "Pregledna karta",
      "lblLegend": "Legenda",
      "lblGeocoder": "Naslov, kraj in iskalnik geoobjektov",
      "lblGeocoderNoFeatures": "Iskalnik naslova in kraja",
      "tooltipGeocoder": "Omogočite svojim bralcem, da po vaši karti iščejo naslove, kraje in/ali geoobjekte. Iskalne možnosti je mogoče konfigurirati na strani elementov spletne karte pod Nastavitve > Spletna karta > Aplikacija > Najdi lokacije.",
      "tooltipGeocoderNoEdit": "Omogočite svojim bralcem, da po karti iščejo naslove, kraje in/ali geoobjekte.",
      "tooltipGeocoderNoFeatures": "Omogočite svojim bralcem, da po tej karti iščejo naslove in kraje. Da omogočite iskanje geoobjektov, prosite lastnika te karte, da jo konfigurira na strani elementov spletne karte pod Nastavitve > Spletna karta > Aplikacija > Najdi lokacije.",
      "linkGeocoder": "Konfiguriraj iskanje po karti",
      "tooltipGeocoderLink": "Uporabite to povezave za konfiguriranje iskanja geoobjektov in drugih možnosti iskanja. Za več informacij glejte temo pomoči ArcGIS »Konfiguriranje iskanja geoobjektov«.",
      "lblEsriGeocoder": "Iskalec krajev",
      "placeholderGenericGeocoder": "Najdi naslov ali kraj",
      "loadingTitle": "Nalaganje imena",
      "entry": "Vnos",
      "entries": "Vnosi",
      "section": "Razdelek",
      "sections": "Razdelki",
      "and": "in",
      "action": "Dejanje v razdelku",
      "actions": "Dejanje v razdelkih",
      "originalWebmap": "Karta je uporabljena za objavo %TPL_NAME%",
      "browseMaps": "Izberi karto",
      "createMap": "Ustvari karto",
      "noResults": "Ni najdenih rezultatov",
      "loadingResults": "Nalaganje ...",
      "current": "Trenutna karta",
      "select": "Izberi ali ustvari karto",
      "newMap": "Novo izbrana karta",
      "newCreatedMap": "Novo ustvarjena karta",
      "webmapDefault": "Privzeta karta",
      "customCfg": "Konfiguracija po meri",
      "tooltipLocation": "Določite lokacijo, ki jo bo prikazala ta karta.",
      "tooltipContent": "Določite vidne sloje.",
      "tooltipPopup": "Izberite pojavno okno, ki se bo odprlo pri prikazu te karte.",
      "tooltipOverview": "Prikaži majhno pregledno karto skupaj z glavno karto.",
      "tooltipLegend": "Prikaži legendo na karti, kar je uporabno, ko ima karta veliko slojev in simbolov.",
      "mapCfgInvite": "Uporabite te ukaze za konfiguracijo svoje karte",
      "lblLocationAlt": "Podedovano s prve karte",
      "tooltipLocationAlt": "Lokacija te karte je sinhronizirana s prvo karto v seriji. Za spremembo tega vedenja serije pojdite na Nastavitve > Možnosti karte."
    },
    "configure": {
      "btnReset": "Ponastavite",
      "btnCancel": "Prekliči",
      "tocTitle": "Vsebina karte",
      "tocExplain": "Izberite sloje, ki bodo prikazani.",
      "tocNoData": "Nobenega sloja ni mogoče konfigurirati",
      "tocSave": "Shrani vsebino karte",
      "extentTitle": "Lokacija karte",
      "extentExplain": "Premikajte se po karti in jo povečajte, da določite, kako bo videti za vaše bralce.",
      "extentSave": "Shranite lokacijo karte",
      "popupTitle": "Pojavno okno karte",
      "popupExplain": "Kliknite na geoobjekt, da odprete pojavno okno, ki ga želite prikazati.",
      "popupSave": "Shranite konfiguracijo pojavnega okna",
      "hintNavigation": "Navigacija po karti je onemogočena."
    },
    "editor": {
      "loading": "Počakajte, da se urejevalnik kart naloži",
      "newTitle": "Ustvari novo karto",
      "editTitle": "Uredi karto",
      "titleLbl": "Ime",
      "titlePh": "Ime karte ...",
      "folderLbl": "Karta bo ustvarjena v isti mapi kot zgodba.",
      "creating": "Ustvarjanje karte",
      "saving": "Shranjevanje karte",
      "success": "Karta je shranjena",
      "successCreate": "Karta je ustvarjena",
      "cancelTitle": "Opustim vse neshranjene spremembe?",
      "close": "Trenutna drsnica",
      "save": "Shrani",
      "confirm": "Da, zapri karto",
      "deny": "Ne, nadaljuj z delom",
      "errorDuplicate": "Karto s tem imenom že imate",
      "errorCreate": "Karte ni mogoče ustvariti. Poskusite znova.",
      "errorSave": "Karte ni mogoče shraniti. Poskusite znova.",
      "notavailable1": "Oprostite, ustvarjanje ali urejanje karte v brskalniku Firefox ni podprto zaradi tehničnih omejitev. Svojo zgodbo lahko izdelate s pomočjo drugega spletnega brskalnika ali uporabite naslednjo nadomestno rešitev.",
      "notavailable2": "Oprostite, ustvarjanje ali urejanje karte ni podprto, ker se aplikacija karte z zgodbo ne nahaja v %PRODUCT%. Za več informacij se obrnite na svojega administratorja ArcGIS.",
      "notavailable3": "Oprostite, ustvarjanje ali urejanje karte ni podprto v tej različici Portal for ArcGIS (potrebna je različica 10.4 ali novejša). Za več informacij se obrnite na svojega administratorja ArcGIS.",
      "notavailable4": "Karto lahko ustvarite z uporabo %MV%, nato se vrnite sem in jo dodajte svoji zgodbi.",
      "notavailable5": "Karto lahko uredite z uporabo %MV%, nato se vrnite sem in kliknite %apply%, da vidite svoje spremembe.",
      "notavailable6": "pregledovalnik kart",
      "notavailable7": "ponovno naloži karto"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizacija",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Moja vsebina",
        "favoritesLabel": "Moje priljubljene"
      },
      "title": "Izberi karto",
      "searchTitle": "Išči",
      "ok": "V redu",
      "cancel": "Prekliči",
      "placeholder": "Vnesite iskalni izraz ali ID spletne karte ..."
    }
  }
});