define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Peta",
      "lblLocation": "Lokasi",
      "lblContent": "Konten",
      "lblPopup": "Pop-up",
      "lblControls": "Ekstra",
      "lblOverview": "Inset Peta",
      "lblLegend": "Legenda",
      "lblGeocoder": "Pencari Alamat atau Tempat",
      "tooltipGeocoder": "Perkenankan pengguna Anda menemukan alamat dan tempat pada peta Anda.",
      "loadingTitle": "Memuat judul",
      "entry": "Entri",
      "entries": "Entri",
      "section": "Bagian",
      "sections": "Bagian",
      "and": "dan",
      "action": "Tindakan di bagian",
      "actions": "Tindakan di bagian",
      "originalWebmap": "Peta digunakan untuk menerbitkan %TPL_NAME%",
      "browseMaps": "Pilih peta",
      "createMap": "Buat peta",
      "current": "Peta saat ini",
      "select": "Pilih atau buat peta",
      "newMap": "Peta yang baru terpilih",
      "newCreatedMap": "Peta yang baru dibuat",
      "webmapDefault": "Default peta",
      "customCfg": "Konfigurasi kustom",
      "tooltipLocation": "Tentukan lokasi yang akan menampilkan peta.",
      "tooltipContent": "Tentukan lapisan yang terlihat.",
      "tooltipPopup": "Pilih pop-up yang akan dibuka saat peta ini ditampilkan.",
      "tooltipOverview": "Tampilkan inset peta kecil bersamaan dengan peta utama.",
      "tooltipLegend": "Tampilkan legenda pada peta, legenda ini berguna jika peta memiliki banyak lapisan dan simbol.",
      "mapCfgInvite": "Gunakan kontrol ini untuk mengonfigurasikan peta Anda",
      "lblLocationAlt": "Diwarisi dari peta pertama",
      "tooltipLocationAlt": "Lokasi peta ini diselaraskan ke peta pertama pada rangkaian. Untuk mengubah perilaku untuk rangkaian ini, buka Pengaturan > Opsi Peta."
    },
    "configure": {
      "btnReset": "Atur ulang",
      "btnCancel": "Batal",
      "tocTitle": "Konten Peta",
      "tocExplain": "Pilih lapisan yang akan ditampilkan.",
      "tocNoData": "Tidak ada lapisan yang dapat dikonfigurasikan.",
      "tocSave": "Simpan konten peta",
      "extentTitle": "Lokasi peta",
      "extentExplain": "Geser dan zoom peta untuk menentukan tampilan peta bagi pembaca.",
      "extentSave": "Simpan lokasi Peta",
      "popupTitle": "Pop-up peta",
      "popupExplain": "Klik fitur untuk membuka pop-up yang ingin Anda tampilkan.",
      "popupSave": "Simpan konfigurasi pop-up",
      "hintNavigation": "Navigasi peta dinonaktifkan."
    },
    "editor": {
      "loading": "Harap tunggu selagi editor peta sedang memuat",
      "newTitle": "Buat peta baru",
      "editTitle": "Edit peta",
      "titleLbl": "Judul",
      "titlePh": "Judul peta...",
      "folderLbl": "Peta akan dibuat di folder yang sama dengan folder cerita.",
      "creating": "Membuat peta",
      "saving": "Menyimpan peta",
      "success": "Peta disimpan",
      "successCreate": "Peta dibuat",
      "cancelTitle": "Buang perubahan yang belum disimpan?",
      "errorDuplicate": "Anda sudah memiliki peta dengan judul yang sama",
      "errorCreate": "Tidak dapat membuat peta. Silakan coba lagi.",
      "errorSave": "Tidak dapat menyimpan peta. Silakan coba lagi.",
      "notavailable1": "Maaf, membuat atau mengedit peta tidak didukung di Firefox karena batasan teknis. Anda mungkin ingin membuat cerita menggunakan browser web berbeda atau gunakan solusi sementara berikut.",
      "notavailable2": "Maaf, membuat atau mengedit peta tidak didukung karena aplikasi peta cerita tidak di-host di %PRODUCT%. Hubungi administrator ArcGIS untuk informasi selengkapnya.",
      "notavailable3": "Maaf, membuat atau mengedit peta tidak didukung pada versi Portal untuk ArcGIS ini (perlu versi 10.4 atau lebih baru). Hubungi administrator ArcGIS untuk informasi selengkapnya.",
      "notavailable4": "Anda dapat membuat peta menggunakan %MV%, lalu kembali ke halaman ini untuk menambahkannya ke cerita Anda.",
      "notavailable5": "Anda dapat mengedit peta menggunakan %MV%, lalu kembali ke halaman ini dan %apply% untuk melihat perubahan Anda.",
      "notavailable6": "penampil peta",
      "notavailable7": "memuat ulang peta"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Organisasi Saya",
        "onlineLabel": "ArcGIS Daring",
        "contentLabel": "Konten Saya",
        "favoritesLabel": "Favorit Saya"
      },
      "title": "Pilih peta",
      "searchTitle": "Cari",
      "ok": "Oke",
      "cancel": "Batal",
      "placeholder": "Masukkan istilah pencarian atau ID peta web..."
    }
  }
});