define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Mapa",
      "lblLocation": "Umiestnenie",
      "lblContent": "Obsah",
      "lblPopup": "Kontextové okno",
      "lblControls": "Doplnky",
      "lblOverview": "Prehľadová mapa",
      "lblLegend": "Legenda",
      "lblGeocoder": "Adresa, miesto a vyhľadávač prvkov",
      "lblGeocoderNoFeatures": "Adresa a vyhľadávač miesta",
      "tooltipGeocoder": "Umožnite svojim čitateľom vyhľadávať na mape adresy, miesta a/alebo prvky. Možnosti vyhľadávania je možné nakonfigurovať na stránke s položkami na webovej mape v časti Nastavenia > Mapa webu > Aplikácia > Nájsť miesta.",
      "tooltipGeocoderNoEdit": "Umožnite svojim čitateľom vyhľadávať na mape adresy, miesta a/alebo prvky.",
      "tooltipGeocoderNoFeatures": "Umožnite svojim čitateľom vyhľadávať na tejto mape adresy a miesta. Ak chcete povoliť vyhľadávanie prvkov, požiadajte vlastníka tejto mapy, aby ho nakonfiguroval na stránke s položkami na webovej mape v časti Nastavenia > Mapa webu > Aplikácia > Nájsť umiestnenia.",
      "linkGeocoder": "Nakonfigurovať vyhľadávanie na mape",
      "tooltipGeocoderLink": "Pomocou tohto odkazu môžete nakonfigurovať vyhľadávanie prvkov a ďalšie možnosti vyhľadávania. Pre viac informácií si prečítajte si témy pomocníka ArcGIS & quot; Konfigurovať vyhľadávanie prvkov & quot;.",
      "lblEsriGeocoder": "Svetový vyhľadávač",
      "placeholderGenericGeocoder": "Nájsť adresu alebo miesto",
      "loadingTitle": "Načítava sa názov",
      "entry": "Údaj",
      "entries": "Údaje",
      "section": "Časť",
      "sections": "Časti",
      "and": "a",
      "action": "Činnosť v časti",
      "actions": "Činnosť v častiach",
      "originalWebmap": "Mapa sa používa na zverejnenie %TPL_NAME%",
      "browseMaps": "Vybrať mapu",
      "createMap": "Vytvoriť mapu",
      "noResults": "Neboli nájdené žiadne výsledky",
      "loadingResults": "Načítava sa...",
      "current": "Aktuálna mapa",
      "select": "Vybrať alebo vytvoriť mapu",
      "newMap": "Novo vybraná mapa",
      "newCreatedMap": "Novo vytvorená mapa",
      "webmapDefault": "Predvolená mapa",
      "customCfg": "Vlastné nastavenie",
      "tooltipLocation": "Definovať polohu, ktorá sa bude zobrazovať na mape.",
      "tooltipContent": "Definovať viditeľné vrstvy.",
      "tooltipPopup": "Vybrať kontextové okno, ktoré sa otvorí po zobrazení tejto mapy.",
      "tooltipOverview": "Zobraziť malú prehľadovú mapu spolu s hlavnou mapou.",
      "tooltipLegend": "Zobraziť na mape legendu mapy, čo je užitočné, keď má mapa veľa vrstiev a symbolov.",
      "mapCfgInvite": "Na konfiguráciu svojej mapy použite tieto ovládacie prvky",
      "lblLocationAlt": "Zdedené z prvej mapy",
      "tooltipLocationAlt": "Toto miesto na mape je synchronizované s prvou mapou v sérii. Ak chcete zmeniť toto správanie svojej série, prejdite na Nastavenia > Možnosti mapy."
    },
    "configure": {
      "btnReset": "Obnoviť",
      "btnCancel": "Zrušiť",
      "tocTitle": "Obsah mapy",
      "tocExplain": "Vyberte, ktoré vrstvy sa majú zobraziť.",
      "tocNoData": "Nie je možné nastaviť žiadnu vrstvu.",
      "tocSave": "Uložiť obsah mapy",
      "extentTitle": "Polohu na mape",
      "extentExplain": "Posúvaním a priblížením mapy môžete určiť, ako bude vyzerať pre vašich čitateľov.",
      "extentSave": "Uložiť umiestnenie na mape",
      "popupTitle": "Kontextové okno mapy",
      "popupExplain": "Kliknutím na prvok otvoríte kontextové okno, ktoré chcete zobraziť.",
      "popupSave": "Uložiť nastavenie kontextového okna",
      "hintNavigation": "Navigácia v mape je vypnutá."
    },
    "editor": {
      "loading": "Počkajte, kým sa načíta editor máp",
      "newTitle": "Vytvoriť novú mapu",
      "editTitle": "Upraviť mapu",
      "titleLbl": "Názov",
      "titlePh": "Názov mapy...",
      "folderLbl": "Mapa bude vytvorená v rovnakom priečinku ako príbeh.",
      "creating": "Vytváranie mapy",
      "saving": "Ukladám mapu",
      "success": "Mapa bola uložená",
      "successCreate": "Mapa bola vytvorená",
      "cancelTitle": "Zahodiť neuložené zmeny?",
      "close": "Zatvoriť",
      "save": "Uložiť",
      "confirm": "Áno, zatvoriť mapu",
      "deny": "Nie, ešte pracujem",
      "errorDuplicate": "Už máte mapu s týmto názvom",
      "errorCreate": "Nebolo možné vytvoriť mapu. Skúste prosím znova.",
      "errorSave": "Nie je možné uložiť mapu. Skúste prosím znova.",
      "notavailable1": "Ľutujeme, vytvorenie alebo úprava mapy nie je v prehliadači Firefox podporovaná z dôvodu technických obmedzení. Možno budete chcieť vytvoriť svoj príbeh pomocou iného webového prehľadávača alebo použiť nasledujúce riešenie.",
      "notavailable2": "Je nám ľúto, vytváranie alebo úprava mapy nie je podporovaná, pretože aplikácia na pridanie príbehu k mape nie je hostovaná v %PRODUCT%. Pre viac informácií kontaktujte svojho správcu ArcGIS.",
      "notavailable3": "Ľutujeme, vytvorenie alebo úprava mapy nie je v tejto verzii portálu pre ArcGIS podporovaná (vyžaduje verziu 10.4 alebo vyššiu). Pre viac informácií kontaktujte svojho správcu ArcGIS.",
      "notavailable4": "Mapu môžete vytvoriť pomocou %MV%, potom sa vráťte späť a pridajte ju do príbehu.",
      "notavailable5": "Mapu môžete upraviť pomocou %MV% , potom sa vráťte späť a%apply% zobrazte zmeny.",
      "notavailable6": "zobrazovač máp",
      "notavailable7": "opäť načítať mapu"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Moja organizácia",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Môj obsah",
        "favoritesLabel": "Moje obľúbené"
      },
      "title": "Vybrať mapu",
      "searchTitle": "Vyhľadávanie",
      "ok": "Ok",
      "cancel": "Zrušiť",
      "placeholder": "Zadať hľadaný výraz alebo ID webovej mapy..."
    }
  }
});