define({
	root: ({
		commonWebmap: {
			selector: {
				lblWebMap: "Web map",
				lblLocation: "Location",
				lblContent: "Content",
				lblPopup: "Popup",
				lblControls: "Extras",
				lblOverview: "Overview Map",
				lblLegend: "Legend",
				loadingTitle: "Loading title",
				entry: "Entry",
				entries: "Entries",
				section: "Section",
				sections: "Sections",
				and: "and",
				action: "Action in section",
				actions: "Action in sections",
				originalWebmap: "Web map used to publish the %TPL_NAME%",
				browseMaps: "Browse for Maps",
				current: "Current web map",
				select: "Select a web map",
				newMap: "Newly selected web map",
				webmapDefault: "Web map default",
				customCfg: "Custom configuration",
				tooltipLocation: "Define the location that this map will display.",
				tooltipContent: "Define the visible layers.",
				tooltipPopup: "Choose a popup that will be opened when this map is displayed.",
				tooltipOverview: "Display a small overview map along with the main map.",
				tooltipLegend: "Display the map legend on the map, helpful when the map has many layers and symbols.",
				mapCfgInvite: "Use these controls to configure your map",
				lblLocationAlt: "Inherited from the first map",
				tooltipLocationAlt: "This map's location is synchronized to the first map in the series. To change this behavior for your series go to Settings > Map Options."
			},
			configure: {
				btnReset: "Reset",
				btnCancel: "Cancel",
				tocTitle: "Map content",
				tocExplain: "Select which layers will be shown.",
				tocNoData: "No layer can be configured.",
				tocSave: "Save map content",
				extentTitle: "Map location",
				extentExplain: "Pan and zoom the map to define how it will look for your readers.",
				extentSave: "Save Map location",
				popupTitle: "Map popup",
				popupExplain: "Click on a feature to open the popup you want to display.",
				popupSave: "Save the popup configuration",
				hintNavigation: "Map navigation is disabled."
			}
		},
		configure: {
			mapdlg:{
				items:{
					organizationLabel: "My Organization",
					onlineLabel: "ArcGIS Online",
					contentLabel: "My Content",
					favoritesLabel: "My Favorites"
				},
				title: "Select Web Map",
				searchTitle: "Search",
				ok: "Ok",
				cancel: "Cancel",
				placeholder: "Enter search term or Web Map ID..."
			}
		}
	}),
	"ar": 1,
	"cs": 1,
	"da": 1,
	"de": 1,
	"el": 1,
	"es": 1,
	"et": 1,
	"fi": 1,
	"fr": 1,
	"he": 1,
	"it": 1,
	"ja": 1,
	"ko": 1,
	"lt": 1,
	"lv": 1,
	"nl": 1,
	"nb": 1,
	"pl": 1,
	"pt-br": 1,
	"pt-pt": 1,
	"ro": 1,
	"ru": 1,
	"sv": 1,
	"th": 1,
	"tr": 1,
	"vi": 1,
	"zh-cn": 1
});
