define({
  "commonWebmap": {
    "selector": {
      "lblWebMap": "Kaart",
      "lblLocation": "Locatie",
      "lblContent": "Content",
      "lblPopup": "Pop-upvenster",
      "lblControls": "Extra's",
      "lblOverview": "Overzichtskaart",
      "lblLegend": "Legenda",
      "lblGeocoder": "Adres, plaats, en Feature Finder",
      "lblGeocoderNoFeatures": "Adres en plaatsvinder",
      "tooltipGeocoder": "Laat uw lezers zoeken naar adressen, plaatsen en/of objecten op uw kaart. Zoekopties kunnen worden geconfigureerd op de itempagina van een webmap onder Instellingen> Web Map> Applicatie> Locaties zoeken.",
      "tooltipGeocoderNoEdit": "Laat uw lezers zoeken naar adressen, plaatsen en/of features op de kaart.",
      "tooltipGeocoderNoFeatures": "Laat uw lezers zoeken naar adressen en plaatsen op deze kaart. Om zoeken naar features in te schakelen, vraagt u de eigenaar van deze kaart om het te configureren op de itempagina van de webmap onder Instellingen> Web Map> Applicatie> Locaties zoeken.",
      "linkGeocoder": "Kaart zoeken configureren",
      "tooltipGeocoderLink": "Gebruik deze link om zoeken naar features te configureren alsmede andere zoekopties. Zie het ArcGIS Help-onderwerp &quot;Zoeken naar feature configureren&quot; voor meer informatie.",
      "lblEsriGeocoder": "World Placefinder",
      "placeholderGenericGeocoder": "Adres of plaats zoeken",
      "loadingTitle": "Titel laden",
      "entry": "Invoer",
      "entries": "Invoer",
      "section": "Sectie",
      "sections": "Secties",
      "and": "en",
      "action": "Actie in sectie",
      "actions": "Actie in secties",
      "originalWebmap": "Kaart die wordt gebruikt om de %TPL_NAME% te publiceren",
      "browseMaps": "Een kaart selecteren",
      "createMap": "Een kaart maken",
      "noResults": "Geen resultaten gevonden",
      "loadingResults": "Laden...",
      "current": "Huidige kaart",
      "select": "Selecteer of maak een kaart",
      "newMap": "Nieuw geselecteerde kaart",
      "newCreatedMap": "Nieuw gemaakte kaart",
      "webmapDefault": "Kaartstandaard",
      "customCfg": "Aangepaste configuratie",
      "tooltipLocation": "Definieer de locatie die deze kaart zal weergeven.",
      "tooltipContent": "Definieer de zichtbare kaartlagen.",
      "tooltipPopup": "Kies een pop-upvenster dat geopend wordt als deze kaart wordt weergegeven.",
      "tooltipOverview": "Geef een kleine overzichtskaart weer samen met de hoofdkaart.",
      "tooltipLegend": "Geef de kaartlegenda weer op de kaart. Dit is handig als de kaart verschillende lagen en symbolen heeft.",
      "mapCfgInvite": "Gebruik deze bedieningselementen om uw kaart te configureren",
      "lblLocationAlt": "Overgenomen van de eerste kaart",
      "tooltipLocationAlt": "De locatie van deze kaart is gesynchroniseerd met de eerste kaart in de serie. Om dit gedrag te wijzigen voor uw serie gaat u naar Instellingen > Kaartopties."
    },
    "configure": {
      "btnReset": "Opnieuw instellen",
      "btnCancel": "Annuleren",
      "tocTitle": "Kaartcontent",
      "tocExplain": "Selecteer welke kaartlagen zullen worden weergegeven.",
      "tocNoData": "Er kan geen kaartlaag worden geconfigureerd.",
      "tocSave": "Kaartcontent opslaan",
      "extentTitle": "Kaartlocatie",
      "extentExplain": "Pan en zoom op de kaart om te definiëren hoe deze eruit zal zien voor uw lezers.",
      "extentSave": "Kaartlocatie opslaan",
      "popupTitle": "Map pop-up",
      "popupExplain": "Klik op een object op de pop-up te openen die u wilt weergeven.",
      "popupSave": "Pop-up-configuratie opslaan",
      "hintNavigation": "Kaartnavigatie is uitgeschakeld."
    },
    "editor": {
      "loading": "Even geduld terwijl we de kaarteditor laden",
      "newTitle": "Nieuwe kaart maken",
      "editTitle": "Kaart bewerken",
      "titleLbl": "Titel",
      "titlePh": "Kaarttitel...",
      "folderLbl": "De kaart zal aangemaakt worden in dezelfde map als het verhaal.",
      "creating": "De kaart aanmaken",
      "saving": "De kaart opslaan",
      "success": "Kaart opgeslagen",
      "successCreate": "Kaart aangemaakt",
      "cancelTitle": "Niet-bewaarde wijzigingen verwijderen?",
      "close": "Sluiten",
      "save": "Opslaan",
      "confirm": "Ja, kaart sluiten",
      "deny": "Nee, blijf werken",
      "errorDuplicate": "U heeft al een kaart met die titel",
      "errorCreate": "Kan de kaart niet maken. Probeer het opnieuw.",
      "errorSave": "Kan de kaart niet opslaan. Probeer het opnieuw.",
      "notavailable1": "Het spijt ons; het aanmaken of bewerken van een kaart wordt niet ondersteund in Firefox omwille van een technische beperking. Creëer uw verhaal d.m.v. een andere webbrowser of gebruik de volgende oplossing.",
      "notavailable2": "Het spijt ons; het aanmaken of bewerken van een kaart wordt niet ondersteund omdat de story map applicatie niet gehost wordt in %PRODUCT%. Neem contact op met uw ArcGIS beheerder voor meer informatie.",
      "notavailable3": "Het spijt ons; het aanmaken of bewerken van een kaart wordt niet ondersteund in deze versie van Portal for ArcGIS (versie 10.4 of hoger vereist). Neem contact op met uw ArcGIS beheerder voor meer informatie.",
      "notavailable4": "U kunt een kaart aanmaken d.m.v. %MV%, en dan hier terugkeren om ze aan uw verhaal toe te voegen.",
      "notavailable5": "U kunt een kaart bewerken d.m.v. %MV%, en dan hier terugkeren om ze aan uw verhaal toe te voegen.",
      "notavailable6": "map viewer",
      "notavailable7": "de kaart opnieuw laden"
    }
  },
  "configure": {
    "mapdlg": {
      "items": {
        "organizationLabel": "Mijn Organisatie",
        "onlineLabel": "ArcGIS Online",
        "contentLabel": "Mijn Content",
        "favoritesLabel": "Mijn Favorieten"
      },
      "title": "Een kaart selecteren",
      "searchTitle": "Zoeken",
      "ok": "OK",
      "cancel": "Annuleren",
      "placeholder": "Voer zoekterm of webmap-ID in..."
    }
  }
});